/* Generated by Together */

package com.javapatterns.prototype.concept2;

public class Client {
    /**
     * @link aggregation
     * @clientRole prototype
     * @clientCardinality 1
     * @supplierCardinality 1..*
     */
    private ConcretePrototype lnkConcretePrototype;
    private ConcretePrototype prototype;

    public void operation(ConcretePrototype example) {
    }
}
